os:
  - linux
language: node_js
branches:
  only:
    - master
node_js:
  - "8"
  - "6"
  - "4"
  - "0.10"
script: "npm run-script test-cover"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
after_failure: "cat /home/travis/build/happner/happner/npm-debug.log"
