os:
  - linux
language: node_js
branches:
  only:
    - master
node_js:
  - '15'
  - '14'
  - '12'
script:
  - npm run lint
  - npm run test-cover
after_script: 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
after_failure: 'cat /home/travis/build/happner/happner/npm-debug.log'
